print("new LOC")
print("1 LOC")
print("2 LOC")
print("7-----------LOC")
print("8----")
print("9............")
print("10............")
print("3-----------LOC")
print(" brach check code")
print(" brach LOC UPDATED")
print(" brach JAIT @@@222222")
